spring.application.name=Backend_TallerAutomotriz

spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.tuprojectref
spring.datasource.password=tupassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=unaclavesecretamuylargarandom123456789
app.jwt.expiration-ms=86400000

stripe.api-key=${STRIPE_SECRET_KEY}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
sb_publishable_txDY3osAp_Cv_0WgIkVBWQ_WX6ZNhPg

server_port=4000